### ISSUE TITLE
`--snap-fix` CLI argument

### ISSUE THREAD

**Issue by samuelcolvin** [15r10nk/inline-snapshot#127]
As per #123, my bad for creating an issue with multiple points.

Please can we have a new `--snap-fix` or `--sfix` argument (or something else concise) which implies both `--inline-snapshot=fix` and `--inline-snapshot=create`.

I'd also be fine if `--sfix` was a concise version of `--inline-snapshot=fix`, and there was a config setting to make `--inline-snapshot=fix` imply `--inline-snapshot=create`.

**Comment by samuelcolvin** [comment]
> I'd also be fine if `--sfix` was a concise version of `--inline-snapshot=fix`.

Or if #128 is sorted, I could have `--inline-snapshot=create` on by default.

**Comment by alexmojaki** [comment]
FWIW I just always use `fix`. When I want to create, I write `assert ... == snapshot(0)`, which requires basically no additional finger movement to type. Then I don't need a different workflow.

**Comment by 15r10nk** [comment]
ok, I think the underlying problem is that everyone has his own workflow and wants a short cli argument for it. What do you think about the idea to provide explicit shortcuts which can be defined by the user in `pyproject.toml`.

``` toml
[tool.inline-snapshot.shortcuts]
sfix="create,fix"
```

This would provide a new pytest option and `pytest --sfix` would be the same as `pytest --inline-snapshot=create,fix`. It would of course also be possible to define several abbreviations.

**Comment by samuelcolvin** [comment]
Sounds good to me!

**Comment by 15r10nk** [comment]
Fixed in 0.14.0

**Comment by samuelcolvin** [comment]
Trucks so much.
