### ISSUE TITLE
Allow specifying where to store external files

### ISSUE THREAD

**Issue by pawamoy** [15r10nk/inline-snapshot#75]
Currently [`outsource`](https://15r10nk.github.io/inline-snapshot/outsource/#inline_snapshot.outsource) only allows to specify a suffix (file extension).

It seems to write external file where the Pytest configuration file is located (sent #74 to make this more clear).

I would prefer to store them under the `tests/snapshots` folder.

Maybe `outsource` could support a new parameter named `dest` or similar?

**Comment by 15r10nk** [comment]
`outsource()` can be used inside some function, which can also be a function in another library (a testing library which makes screenshots for example).

This library should only specify that some value should be stored in an extra file (because it is large for example). They should not be able to specify where exactly this value is stored.

I think it would be better to specify the storage path in the pyproject.toml (for the current storage protocol which will in the future be called "hash:"). Or do you want it to be a different location for different external objects? I would accept a PR if a pyproject.toml option is ok for you.

I'm currently working again on external. This is my current plan https://github.com/15r10nk/inline-snapshot/issues/86#issuecomment-2530805994. 

I don't want to add any new arguments to `outsource()` now. This would make the re-implementation only more difficult.

But Feedback is very welcome. I want to implement it flexible enough to support different use cases. You should then be able to specify the storage protocol in the external name (see the #86 for more information).

**Comment by pawamoy** [comment]
That makes a lot of sense, thanks.

> I would accept a PR if a pyproject.toml option is ok for you.

That's great because I've done just that in a fork already :smile: It works well. There's just one small thing regarding finding pyproject.toml to fix first, so I'll send two PRs :slightly_smiling_face:
